services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"
    volumes:
      - ./config/litellm.yaml:/app/config.yaml
    command: --config /app/config.yaml

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    depends_on:
      - litellm
      - qdrant
    ports:
      - "3000:8080"
    environment:
      OLLAMA_BASE_URL: "http://ollama:11434"
      OPENAI_API_BASE_URL: "http://litellm:4000/v1"
      OPENAI_API_KEY: "sk-1234"
      VECTOR_DB: "qdrant"
      QDRANT_URI: "http://qdrant:6333"
    volumes:
      - open-webui:/app/backend/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

#  postgres:
#    image: pgvector/pgvector:pg17
#    container_name: pgvector
#    restart: unless-stopped
#    environment:
#      POSTGRES_DB: openwebui_vectors
#      POSTGRES_USER: openwebui
#      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data

volumes:
  qdrant_data:
  ollama:
  open-webui:
